apiVersion: v2
name: unified-api
description: Unified Platform REST API
type: application
version: 0.1.0
appVersion: "0.0.0"
maintainers:
  - name: Elskov Platform
    email: elskovservices@gmail.com
