apiVersion: v1
kind: Service
metadata:
  name: {{ include "unified-admin.fullname" . }}
  labels: {{- include "unified-admin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector: {{- include "unified-admin.selectorLabels" . | nindent 4 }}
