name: Terraform Plan (dev)

on:
  pull_request:
    paths: ['infra/terraform/**', '.github/workflows/terraform-plan.yml']

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AWS_REGION: us-east-1
  TF_VERSION: '1.9.4'

jobs:
  plan:
    name: terraform plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform/envs/dev
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - run: terraform fmt -check -recursive
      - run: terraform init -backend=false
      - run: terraform validate
      - run: terraform plan -no-color
